name: ReleaseWorkflow

on:
  release:
#    types: [published, prereleased]
    types: [tagged]


jobs:
  createSentryRelease:
    runs-on: ubuntu-latest
    steps:
      - name: release
          uses: actions/create-release@v1
          id: create_release
          with:
            draft: true
            prerelease: true
            release_name: ${{ github.ref }}
            tag_name: ${{ github.ref }}
            body_path: CHANGELOG.md
          env:
            GITHUB_TOKEN: ${{ github.token }}
      - name: Checkout code
        uses: actions/checkout@master
      - name: Create a Sentry.io release
        uses: tclindner/sentry-releases-action@v1.2.0
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          SENTRY_ORG: thoser666_org
          SENTRY_PROJECT: thoser666_org
        with:
          tagName: ${{ github.ref }}
          environment: qa

