name: Bump version
on:
  push:
    branches:
      - release.*
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Github Tag with semantic versioning
        uses: hennejg/github-tag-action@v4.2.4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          release_branches: release.*,hotfix.*,bugfix.*
