name: Bump version
on:
  push:
    branches:
      - release/*
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@release/v0.0.1-alpha
      - name: Github Tag with semantic versioning
        uses: hennejg/github-tag-action@v4.3.1

        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}